- .github/workflows/ci.yml
- .github/workflows/regression.yml
- package.json
- pnpm-lock.yaml
- scripts/overrideDeps.js
Added workflow to build and tests our packages with various supported `itwinjs-core` and `appui` versions.
Closes https://github.com/iTwin/presentation/issues/65
> Regression testing workflow

- .azure-pipelines/generate-docs.yaml
- .github/workflows/ci.yml
- .github/workflows/regression.yml
Cleaned up pipelines to use same node versions. Removed unused strategy matrix in CI build job.
> Unify node versions used between workflows

- apps/test-app/frontend/src/index.tsx
Added missing docs snippet https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2008782&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=71c8ff40-78b9-5b98-0fd8-62f51b84014f
> Add missing documentation snippet

- apps/test-app/frontend/src/components/properties-widget/PropertiesWidget.tsx
- change/@itwin-presentation-components-28df1f5c-dbeb-4ab5-b32b-aa486e0befd6.json
- packages/components/src/presentation-components/common/ContentDataProvider.ts
- packages/components/src/presentation-components/properties/NavigationPropertyEditor.tsx
- packages/components/src/presentation-components/propertygrid/FavoritePropertiesDataFilterer.ts
- packages/components/src/test/common/ContentDataProvider.test.ts
- packages/components/src/test/properties/NavigationPropertyEditor.test.tsx
- packages/components/src/test/propertygrid/FavoritePropertiesDataFilterer.test.ts
- packages/full-stack-tests/src/frontend/FavoriteProperties.test.ts
- packages/full-stack-tests/src/frontend/providers/FavoritePropertiesDataProvider.test.ts
Closes https://github.com/iTwin/presentation/issues/19
> Add ability to get content field by property description

- apps/test-app/backend/package.json
- apps/test-app/common/package.json
- apps/test-app/frontend/package.json
- change/@itwin-presentation-components-26d258e2-db6a-4cb9-999b-df9d203f624a.json
- change/@itwin-presentation-testing-1734266a-e25e-4cfc-8340-52b4dae2b6f9.json
- package.json
- packages/components/package.json
- packages/testing/package.json
React to changes in itwinjs-core https://github.com/iTwin/itwinjs-core/pull/5316
> Standardize package.json

- .azure-pipelines/generate-docs.yaml
- .github/workflows/release.yml
Closes https://github.com/iTwin/presentation/issues/158
> Tag docs build after release

- change/@itwin-presentation-components-fa6c112a-5147-4890-98fa-86ce4886769b.json
- packages/components/src/presentation-components/tree/DataProvider.ts
- packages/components/src/presentation-components/tree/FilteredDataProvider.ts
- packages/components/src/test/tree/FilteredDataProvider.test.ts
FilteredPresentationTreeDataProvider should create tree node item with same customizations applied as parent `PresentationTreeDataProvider`
> Customize filtered tree node items

- change/@itwin-presentation-components-06688ec7-5106-4748-9a37-419d484b4b3c.json
- packages/components/src/presentation-components/instance-filter-builder/InstanceFilterConverter.ts
- packages/components/src/test/instance-filter-builder/InstanceFilterConverter.test.ts
> Fix filtering when rule contains `Like` operator

- change/@itwin-presentation-components-b925c6c5-0b79-4dec-8849-2cc6e170d8b3.json
- packages/components/src/presentation-components/instance-filter-builder/InstanceFilterConverter.ts
- packages/components/src/test/instance-filter-builder/InstanceFilterConverter.test.ts
> Add filter expression for `Point` type

- .github/workflows/ci.yml
- .github/workflows/regression.yml
- .github/workflows/release-dev.yml
- .github/workflows/release.yml
- packages/components/CHANGELOG.json
- packages/components/CHANGELOG.md
- packages/opentelemetry/CHANGELOG.json
- packages/opentelemetry/CHANGELOG.md
- packages/testing/CHANGELOG.json
- packages/testing/CHANGELOG.md
Closes https://github.com/iTwin/presentation/issues/212
> Fix changelogs

- change/@itwin-presentation-testing-c7701671-3b47-4f84-9be8-3ac05f56ed11.json
- packages/testing/src/presentation-testing.ts
- packages/testing/src/presentation-testing/Helpers.ts
- packages/testing/src/test/Helpers.test.ts
Helpers.ts was not included into "npm run cover". Included it into "npm run cover", and added tests to reach 100% coverage.
> Add tests for Helpers.ts to reach 100% coverage

- .github/workflows/changeset-release.yml
- lage.config.js
- Set correct input for `build` task in `lage`.
- Run `pnpm install` in `changesets` workflow.
> Build fixes

- .changeset/slow-turtles-collect.md
- .github/workflows/regression.yml
- apps/test-app/backend/assets/presentation_rules/ModelElements.PresentationRuleSet.json
- change/@itwin-presentation-components-f212d412-af64-41bb-9ead-04fce4fe46c5.json
- packages/components/package.json
- packages/components/src/presentation-components/tree/DataProvider.ts
- packages/components/src/presentation-components/tree/PresentationTreeNodeItem.ts
- packages/components/src/test/index.ts
- packages/components/src/test/tree/DataProvider.test.ts
- packages/components/src/test/tree/controlled/PresentationTreeNodeRenderer.test.tsx
- packages/components/src/test/tree/controlled/PresentationTreeRenderer.test.tsx
- packages/components/src/test/tree/controlled/UseHierarchyLevelFiltering.test.ts
- packages/full-stack-tests/src/testing/ruleset-testing-snapshots/my-test-hierarchy.snap
- pnpm-lock.yaml
Closes https://github.com/iTwin/presentation/issues/216
When filtering hierarchy level under grouping node combine current filter with filter applied on grouping node hierarchy level.
> Hierarchy level filtering under grouping nodes

- .changeset/orange-dancers-walk.md
- apps/test-app/frontend/package.json
- packages/components/package.json
- pnpm-lock.yaml
Closes https://github.com/iTwin/presentation/issues/290
> Update `itwinui-react` dependency to `2.12.10`

- .changeset/late-years-double.md
- packages/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilterDialog.scss
> Broaden default instance filter builder dialog

- .changeset/polite-turtles-hope.md
- packages/components/src/presentation-components/instance-filter-builder/InstanceFilterBuilder.tsx
- packages/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilterDialog.tsx
- packages/components/src/presentation-components/properties/UniquePropertyValuesSelector.tsx
- packages/components/src/presentation-components/tree/controlled/PresentationTreeRenderer.tsx
- packages/components/src/test/properties/UniquePropertyValuesSelector.test.tsx
> Filter property value selector values based on parent node

- pnpm-lock.yaml
Fixes https://github.com/iTwin/presentation/security/dependabot/15
> Bump `follow-redirects` version

- .changeset/afraid-rats-fly.md
- packages/components/public/locales/en/PresentationComponents.json
Closes https://github.com/iTwin/presentation/issues/415
> Add missing localized string

- .changeset/rich-poets-eat.md
- packages/components/public/locales/en/PresentationComponents.json
- packages/components/src/presentation-components/common/Utils.ts
- packages/components/src/presentation-components/tree/controlled/PresentationTreeRenderer.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/774
> Update filtering dialog results exceed count message

- apps/load-tests/tests/package.json
- pnpm-lock.yaml
Bumped artillery version to resolve https://github.com/iTwin/presentation/security/dependabot/17
> Bump artillery version

- .changeset/gorgeous-plants-nail.md
- packages/components/src/presentation-components/common/ContentBuilder.ts
- packages/components/src/test/common/ContentBuilder.test.ts
Changed struct properties to be sorted.
> Struct property sorting

- .changeset/stupid-seals-sing.md
- packages/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.scss
- packages/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.tsx
Changed tree node action button class to allow buttons to be resized.
> Change tree node action button class

- .changeset/curly-queens-build.md
- packages/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilterDialog.tsx
- packages/components/src/presentation-components/properties/inputs/AsyncSelect.tsx
Fixed unique values dropdown menu impacting other components layout or appearing of screen when rendering inside AppUI widget.
> Fix unique values dropdown layout inside widget

- apps/test-app/frontend/src/components/tree-widget/stateless-v2/UseTree.ts
- apps/test-app/frontend/src/components/tree-widget/stateless-v2/internal/TreeActions.ts
- apps/test-app/frontend/src/components/tree-widget/stateless-v2/internal/TreeLoader.ts
- apps/test-app/frontend/src/components/tree-widget/stateless-v2/internal/TreeModel.ts
- packages/core-interop/api/presentation-core-interop.api.md
- packages/core-interop/src/core-interop/HierarchyLevelDescriptor.ts
- packages/full-stack-tests/src/hierarchy-builder/HierarchyLevelFiltering.test.ts
- packages/full-stack-tests/src/hierarchy-builder/HierarchyValidation.ts
- packages/hierarchy-builder/api/presentation-hierarchy-builder.api.md
- packages/hierarchy-builder/api/presentation-hierarchy-builder.exports.csv
- packages/hierarchy-builder/src/hierarchy-builder/HierarchyNode.ts
Closes https://github.com/iTwin/presentation/issues/443 and https://github.com/iTwin/presentation/issues/410.
> Hierarchy builder: Filtering grouping nodes

- packages/core-interop/src/core-interop/Logging.ts
- packages/core-interop/src/test/Logging.test.ts
- packages/hierarchy-builder/api/presentation-hierarchy-builder.api.md
- packages/hierarchy-builder/api/presentation-hierarchy-builder.exports.csv
- packages/hierarchy-builder/src/hierarchy-builder/HierarchyProvider.ts
- packages/hierarchy-builder/src/hierarchy-builder/Logging.ts
- packages/hierarchy-builder/src/hierarchy-builder/internal/LoggingUtils.ts
- packages/hierarchy-builder/src/hierarchy-builder/internal/operators/DetermineChildren.ts
- packages/hierarchy-builder/src/hierarchy-builder/internal/operators/Grouping.ts
- packages/hierarchy-builder/src/hierarchy-builder/internal/operators/HideIfNoChildren.ts
- packages/hierarchy-builder/src/hierarchy-builder/internal/operators/HideNodesInHierarchy.ts
- packages/hierarchy-builder/src/test/internal/LoggingUtils.test.ts
Don't create the log message if we're not going to log it.
> Hierarchies: Logging improvements

- .changeset/beige-icons-battle.md
- .changeset/config.json
- packages/unified-selection/.npmignore
- packages/unified-selection/LICENSE.md
- packages/unified-selection/package.json
Prepare `@itwin/unified-selection` for initial release
> Setup `@itwin/unified-selection` release

- .changeset/slimy-avocados-sin.md
- packages/core-interop/package.json
- packages/hierarchies/package.json
- packages/unified-selection/package.json
Added missing license field to `package.json`.
> Add missing license field

- .changeset/metal-tables-wonder.md
- packages/components/api/presentation-components.api.md
- packages/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilter.ts
- packages/components/src/test/instance-filter-builder/PresentationInstanceFilter.test.ts
Closes https://github.com/iTwin/presentation/issues/477
> Add API for creating filter conditions compatible with unique values selector

- .github/workflows/benchmark-pr.yml
- .github/workflows/benchmark.yml
- .github/workflows/labeler.yml
> Update Github actions

- .changeset/chatty-apples-admire.md
- .changeset/slow-onions-chew.md
- .vscode/launch.json
- apps/test-app/frontend/src/components/app/App.tsx
- packages/core-interop/src/core-interop/Metadata.ts
- packages/core-interop/src/test/Metadata.test.ts
- packages/unified-selection/api/unified-selection.api.md
- packages/unified-selection/src/test/CachingHiliteSetProvider.test.ts
- packages/unified-selection/src/test/EnableUnifiedSelectionSyncWithIModel.test.ts
- packages/unified-selection/src/test/HiliteSetProvider.test.ts
- packages/unified-selection/src/unified-selection/CachingHiliteSetProvider.ts
- packages/unified-selection/src/unified-selection/EnableUnifiedSelectionSyncWithIModel.ts
- packages/unified-selection/src/unified-selection/HiliteSetProvider.ts
Forgot to do this with https://github.com/iTwin/presentation/pull/553...
> unified-selection: Switched from `ECSchemaProvider` to `ECClassHierarchyInspector`

- .github/workflows/benchmark-hierarchies.yml
- .github/workflows/benchmark-unified-selection.yml
- apps/performance-tests/package.json
- package.json
`benchmark.yml` needs to be split into separate workflows to store test results separately.
> Split benchmark.yml

- packages/hierarchies-react/api/presentation-hierarchies-react.api.md
- packages/hierarchies-react/api/presentation-hierarchies-react.exports.csv
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeRenderer.tsx
- packages/hierarchies-react/src/test/itwinui/Tree.test.tsx
Added ability to render sublabels below tree node labels.
> Hierarchies-react: tree node sublabels

- .changeset/stupid-shrimps-judge.md
- apps/full-stack-tests/src/hierarchies/HierarchyValidation.ts
- apps/full-stack-tests/src/hierarchies/models-tree/ModelsTreeFiltering.test.ts
- packages/hierarchies/src/hierarchies/internal/FilteringHierarchyDefinition.ts
- packages/hierarchies/src/test/HierarchyProvider.test.ts
- packages/hierarchies/src/test/internal/FilteringHierarchyDefinition.test.ts
Fixes https://github.com/iTwin/presentation/issues/602
> `hierarchies`: Fix filter targets with hidden child filter targets

- .changeset/late-otters-smash.md
- packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts
- packages/hierarchies-react/src/test/UseTree.test.tsx
Closes https://github.com/iTwin/presentation/issues/622
> Hierarchies-react: Reset filtered tree state

- .changeset/flat-boxes-fetch.md
- packages/hierarchies/src/hierarchies/internal/FilteringHierarchyDefinition.ts
- packages/hierarchies/src/test/internal/FilteringHierarchyDefinition.test.ts
Closes https://github.com/iTwin/presentation/issues/629
> Hierarchies: Handle filtered path with similar step

- .changeset/thirty-vans-knock.md
- packages/hierarchies-react/src/presentation-hierarchies-react/internal/TreeModel.ts
- packages/hierarchies-react/src/test/internal/TreeActions.test.ts
- packages/hierarchies-react/src/test/internal/TreeModel.test.ts
Changes needed for https://github.com/iTwin/viewer-components-react/issues/923.
> Hierarchies-react: Auto expand node when filter is applied

- .changeset/pretty-melons-add.md
- packages/components/src/presentation-components/properties/inputs/UniquePropertyValuesSelector.tsx
- packages/components/src/test/properties/inputs/UniquePropertyValuesSelector.test.tsx
Fixes needed for https://github.com/iTwin/viewer-components-react/issues/907.
> Components: Fix UniqueValuesSelector not always loading values when searching.

- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.css
- packages/hierarchies-react/src/test/itwinui/Tree.test.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/925.
> Hierarchies-react: show node action buttons when navigating with keyboard

- .changeset/serious-moose-beam.md
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
- packages/hierarchies-react/src/test/itwinui/Tree.test.tsx
Switch focus to "Apply filter" button when "Clear active filter" button is clicked.
> Hierarchies-react: switch focus to apply filter button when filter is cleared

- .github/workflows/benchmark-hierarchies.yml
- .github/workflows/benchmark-unified-selection.yml
- .github/workflows/changeset-release.yml
Switched from `IMJS_ADMIN_GH_TOKEN` to `GITHUB_TOKEN` for pipelines as the token seems to expire.
> Change pipeline token

- .changeset/fair-moons-smell.md
- apps/full-stack-tests/src/IModelUtils.ts
- apps/full-stack-tests/src/hierarchies/Formatting.test.ts
- apps/full-stack-tests/src/hierarchies/HierarchyFiltering.test.ts
- apps/full-stack-tests/src/hierarchies/HierarchyLevelFiltering.test.ts
- apps/full-stack-tests/src/hierarchies/Utils.ts
- apps/full-stack-tests/src/hierarchies/grouping/PropertiesGrouping.test.ts
- apps/full-stack-tests/src/hierarchies/grouping/SpecialCases.test.ts
- apps/full-stack-tests/src/hierarchies/learning-snippets/Formatting.test.ts
- packages/core-interop/src/core-interop/Formatting.ts
- packages/hierarchies/api/presentation-hierarchies.api.md
- packages/hierarchies/learning/Formatting.md
- packages/hierarchies/package.json
- packages/hierarchies/src/hierarchies/NodeSelectQueryFactory.ts
- packages/hierarchies/src/test/NodeSelectQueryFactory.test.ts
- packages/shared/src/shared/Formatting.ts
- packages/shared/src/shared/ecsql-snippets/ECSqlValueSelectorSnippets.ts
- scripts/updateExtractions.js
> Hierarchies: Learning page for node labels' formatting

- apps/full-stack-tests/src/hierarchies/learning-snippets/Localization.test.ts
- packages/hierarchies/learning/Localization.md
> Hierarchies: Add a learning page for localization

- .github/workflows/changeset-release.yml
Reverting changes made in https://github.com/iTwin/presentation/pull/658 and https://github.com/iTwin/presentation/pull/659.
> Revert token in `changeset-release` pipeline

- apps/full-stack-tests/eslint.config.js
- apps/full-stack-tests/package.json
- apps/full-stack-tests/src/hierarchies-react/learning-snipptets/Localization.test.tsx
- apps/full-stack-tests/src/hierarchies-react/learning-snipptets/ReadmeExample.test.tsx
- packages/hierarchies-react/README.md
- packages/hierarchies-react/package.json
- pnpm-lock.yaml
Closes https://github.com/iTwin/presentation/issues/666.
> Hierarchies-react: Update README to use compiled code snippets

- .changeset/nervous-jokes-swim.md
- .changeset/strange-deers-visit.md
- .changeset/tough-queens-repair.md
- apps/full-stack-tests/src/hierarchies/learning-snippets/Formatting.test.ts
- apps/full-stack-tests/src/hierarchies/learning-snippets/Grouping.test.ts
- apps/full-stack-tests/src/hierarchies/learning-snippets/Localization.test.ts
- apps/full-stack-tests/src/hierarchies/learning-snippets/ReadmeExample.test.ts
- apps/full-stack-tests/src/hierarchies/learning-snippets/Utils.ts
- packages/hierarchies/README.md
- packages/hierarchies/api/presentation-hierarchies.api.md
- packages/hierarchies/learning/Formatting.md
- packages/hierarchies/learning/Grouping.md
- packages/hierarchies/learning/Localization.md
- packages/hierarchies/src/hierarchies/NodeSelectQueryFactory.ts
- packages/hierarchies/src/hierarchies/internal/ChildNodeObservablesCache.ts
- packages/hierarchies/src/hierarchies/internal/operators/grouping/PropertiesGrouping.ts
- packages/hierarchies/src/test/HierarchyProvider.test.ts
- packages/hierarchies/src/test/internal/operators/grouping/PropertiesGrouping.test.ts
- packages/test-utilities/src/test-utilities/IModelUtils.ts
> Hierarchies: Learning page for grouping

- apps/full-stack-tests/src/hierarchies/HierarchyValidation.ts
- apps/full-stack-tests/src/hierarchies/learning-snippets/HierarchyDefinitions.test.ts
- packages/hierarchies/learning/HierarchyDefinitions.md
- packages/hierarchies/learning/HierarchyProcessing.md
> Hierarchies: Add a learning page for hierarchy definitions

- apps/full-stack-tests/src/hierarchies/learning-snippets/NodeLabels.test.ts
- packages/hierarchies/learning/NodeLabels.md
- packages/test-utilities/src/test-utilities/IModelUtils.ts
> Hierarchies: Add a learning page for node labels

- apps/test-app/frontend/src/api/MyAppFrontend.ts
- packages/hierarchies/learning/PerformanceTuning.md
> Hierarchies: Add a learning page for performance tuning

- apps/full-stack-tests/src/hierarchies/learning-snippets/Migration.test.ts
- apps/full-stack-tests/tsconfig.json
- packages/hierarchies/README.md
- packages/hierarchies/learning/PresentationRulesMigrationGuide.md
- packages/test-utilities/src/test-utilities/IModelUtils.ts
Part of https://github.com/iTwin/presentation/issues/423.
> Hierarchies: Add a guide for migrating from Presentation Rules system

- packages/hierarchies/README.md
Closes https://github.com/iTwin/presentation/issues/423
> Hierarchies: Reference our learning pages from README

- .changeset/pretty-wolves-help.md
- .changeset/purple-readers-brake.md
- .changeset/stupid-pants-tap.md
- apps/full-stack-tests/src/hierarchies-react/learning-snipptets/Localization.test.tsx
- apps/full-stack-tests/src/hierarchies-react/learning-snipptets/ReadmeExample.test.tsx
- apps/full-stack-tests/src/hierarchies/HierarchyFiltering.test.ts
- apps/full-stack-tests/src/hierarchies/learning-snippets/MergedHierarchies.test.ts
- apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx
- packages/hierarchies-react/README.md
- packages/hierarchies-react/api/presentation-hierarchies-react.api.md
- packages/hierarchies-react/api/presentation-hierarchies-react.exports.csv
- packages/hierarchies-react/src/presentation-hierarchies-react.ts
- packages/hierarchies-react/src/presentation-hierarchies-react/UseIModelTree.ts
- packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts
- packages/hierarchies-react/src/presentation-hierarchies-react/internal/UseUnifiedSelection.ts
- packages/hierarchies-react/src/test/UseIModelTree.test.tsx
- packages/hierarchies-react/src/test/UseTree.test.tsx
- packages/hierarchies-react/src/test/internal/UseUnifiedSelection.test.tsx
- packages/hierarchies/api/presentation-hierarchies.api.md
- packages/hierarchies/learning/MergedHierarchies.md
- packages/hierarchies/src/hierarchies/HierarchyProvider.ts
- packages/hierarchies/src/hierarchies/imodel/IModelHierarchyProvider.ts
- packages/hierarchies/src/test/HierarchyProvider.test.ts
- packages/hierarchies/src/test/imodel/IModelHierarchyProvider.test.ts
Closes https://github.com/iTwin/presentation/issues/702
> Hierarchies-react: Support iModel-agnostic trees

- apps/full-stack-tests/package.json
- packages/models-tree/src/models-tree/ModelsTreeDefinition.ts
- packages/models-tree/src/models-tree/ModelsTreeIdsCache.ts
- pnpm-lock.yaml
Copied from https://github.com/iTwin/viewer-components-react/tree/master/packages/itwin/tree-widget/src/components/trees/models-tree to make sure out test app and tests use the latest version.
> Update models tree definition to the latest version

- apps/load-tests/tests/package.json
- apps/test-app/backend/package.json
- apps/test-app/frontend/package.json
- package.json
- pnpm-lock.yaml
Closes https://github.com/iTwin/presentation/security/dependabot/34
> Bump package dependencies

- .changeset/afraid-panthers-melt.md
https://github.com/iTwin/presentation/pull/791 had a typo...
> Fix changelog message

- pnpm-lock.yaml
Closes https://github.com/iTwin/presentation/security/dependabot/40
> Bump `nanoid`

- .changeset/selfish-toes-promise.md
Fixes code example from https://github.com/iTwin/presentation/pull/807
> `hierarchies-react`: Fix code example

- apps/full-stack-tests/src/hierarchies/learning-snippets/CustomHierarchyProvider.test.ts
- packages/hierarchies/README.md
- packages/hierarchies/learning/CustomHierarchyProviders.md
- packages/hierarchies/learning/HierarchyLevelFiltering.md
- packages/hierarchies/learning/imodel/HierarchyLevelFiltering.md
Closes https://github.com/iTwin/presentation/issues/813
> `hierarchies: Add an example for how to implement hierarchy level filtering in a custom hierarchy provider

- pnpm-lock.yaml
- pnpm-workspace.yaml
Closes https://github.com/iTwin/presentation/issues/787
> Bump `itwinui-react` to `3.16.2`

- .changeset/little-vans-sell.md
- packages/hierarchies-react/api/presentation-hierarchies-react.api.md
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeRenderer.tsx
- packages/hierarchies-react/src/test/itwinui/Tree.test.tsx
closes https://github.com/iTwin/presentation/issues/815
Demo:
https://github.com/user-attachments/assets/5813eb99-5c30-4c1e-9732-5529b12372f2
> Add option to disable button based filtering

- apps/load-tests/tests/package.json
- pnpm-lock.yaml
Closes https://github.com/iTwin/presentation/security/dependabot/45
> Bump `jsonpath-plus` version to `10.3.0`

- apps/test-app/frontend/src/components/app/App.tsx
- apps/test-app/frontend/src/components/tree-widget/MultiDataSourceTree.tsx
- apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx
- packages/hierarchies-react/api/presentation-hierarchies-react.api.md
- packages/hierarchies-react/api/presentation-hierarchies-react.exports.csv
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeErrorRenderer.tsx
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
- pnpm-lock.yaml
- pnpm-workspace.yaml
Update theme bridge usage to make sure dropdowns styling works correctly.
Remove refs from TreeNodeRenderer and co.
Resolve majority of errors logged in console.
Bump itwinui-react version
> Cleanup Tree and test-app

- .changeset/chilly-kids-love.md
- packages/components/api/presentation-components.api.md
- packages/components/src/presentation-components/common/ContentBuilder.ts
- packages/components/src/presentation-components/common/RulesetRegistrationHelper.ts
- packages/components/src/presentation-components/instance-filter-builder/Utils.ts
- packages/components/src/presentation-components/properties/inputs/NumericPropertyInput.tsx
- packages/components/src/test/common/ContentBuilder.test.ts
- packages/components/src/test/propertygrid/UseUnifiedSelection.test.tsx
- packages/testing/src/presentation-testing.ts
- packages/testing/src/presentation-testing/ContentBuilder.ts
- packages/testing/src/presentation-testing/Helpers.ts
One more reason to add the regressions pipeline (https://github.com/iTwin/presentation/issues/869)...
> Components & Testing: Fix `itwinjs-core@4.x` compatibility

- .changeset/healthy-balloons-melt.md
- apps/full-stack-tests/src/IModelUtils.ts
- apps/full-stack-tests/src/Utils.ts
- apps/full-stack-tests/src/hierarchies/Utils.ts
- apps/full-stack-tests/src/hierarchies/learning-snippets/Formatting.test.ts
- apps/full-stack-tests/src/unified-selection/SelectionSync.test.ts
- packages/unified-selection/src/test/EnableUnifiedSelectionSyncWithIModel.test.ts
- packages/unified-selection/src/unified-selection/EnableUnifiedSelectionSyncWithIModel.ts
Closes https://github.com/iTwin/presentation/issues/881.
Really need to add the regressions pipeline (https://github.com/iTwin/presentation/issues/869)...
> Unified selection: Fix `enableUnifiedSelectionSyncWithIModel` with 4.x core

- .changeset/hot-cheetahs-hope.md
- apps/test-app/frontend/package.json
- apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx
- packages/hierarchies-react/package.json
- pnpm-lock.yaml
> [hierarchies-react]: remove ^ from alpha dependencies

- .changeset/config.json
- package.json
- pnpm-lock.yaml
Finish what https://github.com/iTwin/presentation/pull/896 tried to accomplish
Update changesets/cli version
> Do not bump workspace dependencies that do not use workspace protocol

- .changeset/gold-days-end.md
- .changeset/wise-plants-try.md
- apps/test-app/frontend/package.json
- apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx
- packages/hierarchies-react/api/presentation-hierarchies-react.api.md
- packages/hierarchies-react/api/presentation-hierarchies-react.exports.csv
- packages/hierarchies-react/package.json
- packages/hierarchies-react/src/presentation-hierarchies-react.ts
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/LocalizationContext.tsx
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeActionButton.tsx
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeErrorRenderer.tsx
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
- pnpm-lock.yaml
Changes:
- updated itwinUI alpha to 10
- added `ActiveDescription` to action items definition, when a value is provided a dot will appear above action.
Preview (Filter is applied):
Ps. no changes when filter is not used.
> [Hierarchies-react]: filter action active state

- apps/test-app/frontend/package.json
- pnpm-lock.yaml
Closes https://github.com/iTwin/presentation/security/dependabot/48
Closes https://github.com/iTwin/presentation/security/dependabot/50
Closes https://github.com/iTwin/presentation/security/dependabot/49
Closes https://github.com/iTwin/presentation/security/dependabot/47
> Resolve CVEs

- .changeset/good-actors-dance.md
- apps/test-app/frontend/src/components/tree-widget/MultiDataSourceTree.tsx
- apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx
- packages/hierarchies-react/api/presentation-hierarchies-react.api.md
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
closes https://github.com/iTwin/viewer-components-react/issues/1203
Preview:
Could not find a color picker like component in kiwi.
> [Hierarchies-react]: decorators

- .changeset/twenty-berries-collect.md
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/FlatTreeNode.ts
> [Hierarchies-react]: fix level for tree items

- .changeset/sad-mugs-pump.md
- apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeRenderer.tsx
> [Hierarchies-react]: additional scrollbar fix

- .changeset/grumpy-trains-cough.md
- apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx
- packages/hierarchies-react/api/presentation-hierarchies-react.api.md
- packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts
- packages/hierarchies-react/src/presentation-hierarchies-react/Utils.ts
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeActionButton.tsx
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
- packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeRenderer.tsx
Memoized tree components to reduce the amount of renders when interacting with the tree.
> [hierarchies-react]: Memoize components

- .changeset/chatty-hounds-hide.md
- packages/hierarchies-react/src/presentation-hierarchies-react/UseSelectionHandler.ts
- packages/hierarchies-react/src/test/UseSelectionHandler.test.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/1128
> Fix `extended` selection mode

- .changeset/lucky-flies-try.md
Should've done this in https://github.com/iTwin/presentation/pull/952...
> Add change file for releasing patches

- .changeset/moody-doodles-work.md
Release changes that were pulled in after merging in `master`
> Release after merge

- .changeset/modern-eels-chew.md
Release `presentation-core-interop`/`presentation-hierarchies`/`presentation-shared` with 5.0 itwinjs-core changes merged from master.
> Release changes after merge

- .changeset/plain-yaks-shine.md
- .npmrc
- apps/performance-tests/src/hierarchies/ModelsTree.test.ts
- apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx
- packages/hierarchies-react/api/presentation-hierarchies-react.api.md
- packages/hierarchies-react/src/presentation-hierarchies-react/UseIModelTree.ts
- packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts
- packages/hierarchies-react/src/test/UseIModelTree.test.tsx
- packages/hierarchies-react/src/test/UseTree.test.tsx
- packages/models-tree/src/models-tree/ModelsTreeDefinition.ts
closes https://github.com/iTwin/presentation/issues/788
> [Hierarchies-react]: add cancellation to getFilteredPaths

- .changeset/odd-poems-follow.md
- packages/hierarchies-react/api/presentation-hierarchies-react.api.md
- packages/hierarchies-react/api/presentation-hierarchies-react.exports.csv
- packages/hierarchies-react/src/presentation-hierarchies-react.ts
- packages/hierarchies-react/src/presentation-hierarchies-react/stratakit/FlatTreeNode.ts
- packages/hierarchies-react/src/presentation-hierarchies-react/stratakit/TreeRenderer.tsx
Related https://github.com/iTwin/presentation/issues/932
> [Hierarchies-react]: rename flat nodes to flat items

- .changeset/cool-apples-tap.md
Bump and publish new version of `alpha` after changed from master were merged.
> [next]: Version bump

- .changeset/fast-crabs-fold.md
- .changeset/ten-falcons-kiss.md
- CONTRIBUTING.md
- apps/full-stack-tests/src/components/properties/PropertyEditors.test.tsx
- apps/full-stack-tests/src/testing/RulesetTesting.test.ts
- packages/components/src/presentation-components/properties/inputs/UseQuantityValueInput.tsx
- pnpm-lock.yaml
- pnpm-workspace.yaml
- scripts/regression/core-4.10.7.patch
- scripts/regression/core-4.4.0.patch
Part of https://github.com/iTwin/viewer-components-react/issues/1340
> Components: Use `IModelApp.FormatsProvider`
