.github/workflows/codeql-analysis.yml, .github/workflows/release-dev.yml, .github/workflows/release.yml, beachball.config.js
Run dev prerelease publishing workflow on each push to default branch if changes were made to any of publishable packages. Added `[skip actions]` to version bump commit message to avoid recursively running this workflow.
=> Run dev publish on push

packages/full-stack-tests/src/setup.ts
Previous pseudoLocalization implementation in full-stack-test were flagged as security vulnerability https://github.com/iTwin/presentation/security/code-scanning/1 . Although this is not a production code I made an attempt to fix this.
=> Cleanup pseudoLocalization in tests

.github/workflows/release-dev.yml, .github/workflows/release.yml, beachball.config.js, change/@itwin-presentation-components-eba1d12a-c78c-48bb-8816-f7419b77f47e.json, packages/components/src/presentation-components/instance-filter-builder/MultiTagSelect.tsx, packages/components/src/presentation-components/properties/NavigationPropertyTargetSelector.tsx
Added missing css imports in some `PresentationInstanceFilterBuilder` related components. Missing imports resulted in components being rendered without styling in cases when css classes used in those components where nor loaded globally.
Also updated beachball config. Looks like message property from config is used for both `publish` and `change` commands. This resulted in `pnpm change` script generating change files with same message.
=> Add missing css imports

change/@itwin-presentation-components-2a0eeff2-270a-4075-a4bf-8528d8bbb7de.json, packages/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.scss
=> Ensure that the action buttons have the same background color as the parent node in the tree widget

change/@itwin-presentation-components-3a7cdc71-44dc-493e-b5bc-d508816e64e9.json, packages/components/src/presentation-components/properties/NavigationPropertyTargetSelector.tsx
Navigation property value is displayed under the chevron when it's too long:
After this fix, property value would look like this:
closes #79
=> Add white background to the chevron

.github/labeler.yml, .github/workflows/labeler.yml
This should improve discoverability of newly filed issues in this repository.
Ideally, in our project board we'd like to see these issues:
- everything from the `presentation` repo
- with `presentation` label from all other repos
Sadly, github doesn't provide a way to filter with `OR` operator (`repository:"iTwin/presentation" OR label:"presentation"`)... So we need to make sure everything we want to see is labeled with `presentation` label.
=> Add a workflow for labeling all issues with "presentation" label

change/@itwin-presentation-opentelemetry-47692d53-3c7b-4de3-9960-a16572f3bf22.json, packages/opentelemetry/src/presentation-opentelemetry/Diagnostics.ts
Supplement https://github.com/iTwin/presentation/pull/130:
- Add a change log regarding the breaking change
- Improve docs of the new `exportDiagnostics` function
=> OpenTelemetry: Document recent API change

change/@itwin-presentation-testing-bf04a3a7-ea71-4dcf-9118-3329b2ce6594.json, packages/testing/src/presentation-testing/IModelUtilities.ts
Fixed `createFileNameFromString` to replace all spaces into `-` when building test iModel based on test name. Also made sure that consecutive spaces are replaced into one `-`
=> Testing: replace spaces in test name when creating test iModel

apps/test-app/frontend/src/components/app/App.tsx
Without `data-root-container="iui-root-id"` on the root container, none of the `--buic-*` variables work.
=> Apply a hack to get `core-react` styles working in our test app

packages/full-stack-tests/.mocharc.json
Similar to https://github.com/iTwin/itwinjs-core/pull/5638:
> The first run causes core-frontend to copy some .js files to /lib/public/scripts. Then on the second run mocha attempted to load them and failed...
=> Fix mocha attempting to load irrelevant .js files

.github/workflows/ci.yml, .github/workflows/regression.yml, .github/workflows/release.yml
full-stack-tests might segfault on node 18.16.1 because of an issue in `core-backend` https://github.com/iTwin/itwinjs-core/issues/5663#issuecomment-1600764489. Use 18.16.0 in pipelines that run test to avoid bloking PRs and releases.
=> Use node 18.16.0 in pipelines that run tests

apps/test-app/backend/package.json, pnpm-lock.yaml
Fixes `vm2 Sandbox Escape vulnerability`
=> Update `@opentelemetry/sdk-node` to `^0.41.2`

change/@itwin-presentation-components-a970de67-6464-44ae-b7bc-9e203c6b4a10.json, packages/components/src/presentation-components/tree/controlled/UseControlledTreeFiltering.ts, packages/components/src/test/tree/controlled/UseControlledTreeFiltering.test.ts
Closes https://github.com/iTwin/viewer-components-react/issues/573
Reset `filteredNodeLoader` after filter string is changed in order for spinner to be shown while filtering is in progress.
=> Tree filtering: reset `filteredNodeLoader` when filter string is changed

.github/workflows/changeset-release.yml
Updates release workflow using changesets to add `[skip actions][publish docs]` to PR title. This should make sure CI workflow is not run after release is merged and docs is tagged for docs site releases.
=> Update release workflow

.github/workflows/changeset-release.yml
Using `actions/setup-node` action with `repository-url` creates `.npmrc` file that expect to get npm token from env variable `NODE_AUTH_TOKEN`
=> Use correct env variable for npm authorization in release workflow

.changeset/big-weeks-refuse.md, packages/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilterProperty.tsx
Added specific `zIndex` property for the tooltip component. 
The `zIndex` value was chosen by checking what is the value of the parent element, which was _99999_, and adding one additional _9_ to it.
=> Add explicit zIndex for tooltip

.changeset/dry-scissors-rule.md, apps/test-app/frontend/package.json, apps/test-app/frontend/src/components/app/App.tsx, packages/components/src/presentation-components/viewport/ViewportSelectionHandler.ts, packages/components/src/presentation-components/viewport/WithUnifiedSelection.tsx, packages/components/src/test/viewport/WithUnifiedSelection.test.tsx, pnpm-lock.yaml
Closes https://github.com/iTwin/presentation/issues/329
Use new `getHiliteSetIterator` API to highlight elements on unified selection change. This new implementation cancels ongoing hilite set request when unified selection changes again.
=> Cancel hilite set request on selection change

.changeset/funny-feet-buy.md, packages/components/public/locales/en/PresentationComponents.json, packages/components/src/presentation-components/instance-filter-builder/InstanceFilterBuilder.tsx, packages/components/src/test/instance-filter-builder/IntanceFilterBuilder.test.tsx
This PR adds changes to the placeholder value displayed in class selector of the instance filtering dialog to try and signify that selecting a class is optional.
Also, added extra logic to display different text in class selector based on whether any classes are selected or not.
=> Signify Class Selector being Optional in the Filtering Dialog

.changeset/strange-shoes-cheer.md, packages/components/src/presentation-components/instance-filter-builder/InstanceFilterBuilder.tsx, packages/components/src/test/instance-filter-builder/IntanceFilterBuilder.test.tsx
Closes #368 
The previous implementation was not working correctly when everything is rendered twice (strict mode).  This fix is not necessary
when strict mode is disabled.
=> Filter Dialog: retain selected classes information on strict mode rerenders

.changeset/serious-paws-ring.md, packages/components/api/presentation-components.api.md, packages/components/api/presentation-components.exports.csv, packages/components/src/presentation-components/tree/controlled/PresentationTreeRenderer.tsx
I think it is important to note that the `FilterableTreeProps` is subject to change by `documentBodyRef`  getting removed once `itwinui` version is bumped.
=> PresentationTreeRenderer: Adjust API

.changeset/green-windows-cry.md, packages/components/api/presentation-components.api.md, packages/components/api/presentation-components.exports.csv, packages/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilterDialog.tsx, packages/components/src/presentation-components/tree/controlled/PresentationTreeRenderer.tsx, packages/components/src/test/instance-filter-builder/PresentationInstanceFilterDialog.test.tsx, packages/components/src/test/tree/controlled/PresentationTreeRenderer.test.tsx
Updated `PresentationInstanceFilterDialogProps` to make `PresentationInstanceFilterDialog` more convenient to use in case input keys are not now before loading `Descriptore`.
=> `PresentationInstanceFilterDialog`: Make API more convienent

packages/core-interop/api/presentation-core-interop.api.md, packages/core-interop/api/presentation-core-interop.exports.csv, packages/core-interop/src/core-interop/HierarchyLevelDescriptor.ts, packages/core-interop/src/test/HierarchyLevelDescriptor.test.ts, packages/full-stack-tests/src/hierarchy-builder/HierarchyLevelDescriptors.test.ts, packages/full-stack-tests/src/hierarchy-builder/models-tree/ModelsTreeHierarchyLevelFiltering.test.ts
Input keys are needed when loading distinct values using `Hierarchy level descriptor ruleset`
=> [core-interop]: Returns input keys with hierarchy level descriptor

.changeset/proud-numbers-retire.md, packages/components/src/presentation-components/common/PortalTargetContext.tsx, packages/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilterDialog.tsx, packages/components/src/presentation-components/properties/inputs/AsyncSelect.tsx, packages/components/src/test/properties/inputs/UniquePropertyValuesSelector.test.tsx
Closes [439](https://github.com/iTwin/presentation/issues/439)
- Modified `UniqueValueSelector` dropdown menu to open upwards when there is not enough space below.
- Changed the dropdown menu portal target to the filtering dialog instead of the body.
=> Change unique value selector dropdown menu to be space aware

.changeset/large-hotels-fly.md, packages/components/src/presentation-components/properties/inputs/AsyncSelect.tsx
Closes [442](https://github.com/iTwin/presentation/issues/442)
Fixed an issue with `UniqueValueSelector` only loading the first page of values.
=> Load more than one page in UniqueValueSelector

.changeset/smart-lobsters-hide.md, packages/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilterProperty.scss, packages/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilterProperty.tsx
Closes [450](https://github.com/iTwin/presentation/issues/450)
Fixed tooltip appearing under property selector.
=> Fix tooltip appearing under property selector

apps/performance-tests/.mocharc.json, apps/performance-tests/package.json, apps/performance-tests/src/Datasets.ts, apps/performance-tests/src/StatelessHierarchyProvider.ts, apps/performance-tests/src/main.ts, apps/performance-tests/src/stateless.test.ts, apps/performance-tests/src/util/IModelUtilities.ts, apps/performance-tests/src/util/TestReporter.ts, apps/performance-tests/src/util/TestUtilities.ts, packages/full-stack-tests/src/IModelUtils.ts, packages/test-utilities/src/test-utilities/IModelUtils.ts, pnpm-lock.yaml
Closes #424
- Add a custom schema to the 50k element iModel.
- Make elements of the 50k iModel groupable by user label, class and properties.
- Add support for assertions.
- Add `only` and `skip` parameters for the `run` function.
- Add logging of iTwin.js errors.
=> Add performance tests for all grouping types

packages/unified-selection/README.md, packages/unified-selection/api/unified-selection.api.md, packages/unified-selection/src/test/SelectionStorage.test.ts, packages/unified-selection/src/unified-selection/Selectable.ts, packages/unified-selection/src/unified-selection/SelectionStorage.ts
- Add README (part of https://github.com/iTwin/presentation/issues/452)
- Change `SelectionStorage` methods to take a props object rather than a list of arguments to make it more future-proof.
=> Unified selection: Readme and API future-proofing

apps/performance-tests/src/StatelessHierarchyProvider.ts, packages/core-interop/src/core-interop/Metadata.ts
- Use `SchemaJsonLocater` instead of our own implementation.
- Workaround for https://github.com/iTwin/itwinjs-core/issues/6542.
=> Fix same schemas being loaded more than once

.changeset/blue-ligers-clap.md, packages/components/src/presentation-components/table/UsePresentationTable.ts, packages/components/src/test/table/UsePresentationTable.test.tsx
Removed `useUnifiedSelectionContext` usage from `usePresentationTableWithUnifiedSelection`. It does not work with multiple levels which resulted in some selection handling done through `useUnifiedSelectionContext` and some through `Presentation.selection`. Now unified selection in all cases are handled through `Presentation.selection`.
=> Improve unified selection table

apps/performance-tests/package.json, apps/performance-tests/src/util/BlockHandler.ts, apps/performance-tests/src/util/TestReporter.ts, apps/performance-tests/src/util/TestUtilities.ts, pnpm-lock.yaml
Currently performance tests do not account for long main thread blocks that last until the end of the test. 
Now, before stopping the block handler, we will wait until block handler's callback is run the last time before stopping it.
Block handler will now use a much more convenient node's `timers/promises/setInterval` function which returns an async iterator.
Since `blocked` library is very simple and doesn't provide anything of value,  the dependency will be removed in favor of custom blocking time measuring logic.
Additionally, new optional logging will be added which might help the debugging experience:
- Logging of start and end times of the blocks
- Ability to log "pings" of the main thread
=> Fix block handler showing incorrect results

.vscode/settings.json, apps/performance-tests/src/main.ts, packages/core-interop/LICENSE.md, packages/core-interop/README.md, packages/core-interop/api/presentation-core-interop.api.md, packages/core-interop/api/presentation-core-interop.exports.csv, packages/core-interop/src/core-interop/Formatting.ts, packages/core-interop/src/core-interop/HierarchyLevelDescriptor.ts, packages/core-interop/src/core-interop/Logging.ts, packages/core-interop/src/core-interop/Metadata.ts, packages/core-interop/src/core-interop/QueryExecutor.ts, packages/core-interop/src/core-interop/Transactions.ts, packages/core-interop/src/presentation-core-interop.ts, packages/core-interop/src/test/Formatting.test.ts, packages/core-interop/src/test/Logging.test.ts, packages/core-interop/src/test/QueryExecutor.test.ts, packages/full-stack-tests/src/hierarchies/Formatting.test.ts, packages/full-stack-tests/src/hierarchies/models-tree/ModelsTreeCompareWithNative.test.ts
Part of https://github.com/iTwin/presentation/issues/422.
Going to remove `createHierarchyLevelDescriptor` altogether in a separate PR.
=> core-interop: API cleanup, README, LICENSE

.changeset/rare-hotels-bathe.md, .vscode/settings.json, packages/components/api/presentation-components.api.md, packages/components/src/presentation-components/tree/controlled/UseUnifiedSelection.ts
Switched `UnifiedSelectionTreeEventHandler` to use private fields to avoid clashed between private property names when extending it.
=> Use private fields in `UnifiedSelectionTreeEventHandler`

.npmrc, packages/core-interop/package.json, packages/hierarchies/package.json, packages/models-tree/package.json, packages/testing/package.json, packages/unified-selection/package.json, pnpm-lock.yaml
Added missing dev dependencies. Also disabled hoisting for majority of packages and left only those that are needed for things to work:
`ignore-styles`, `global-jsdom`, `source-map-support` for `mocha`
`@types/react*` for build
`*babel*` for `@loaders.gl/schema` used by `@itwin/core-frontend`
=> Add missing dev dependencies

.npmrc, .vscode/launch.json, apps/performance-tests/package.json, packages/components/package.json, packages/core-interop/.mocharc.json, packages/core-interop/package.json, packages/full-stack-tests/package.json, packages/full-stack-tests/src/setup.ts, packages/hierarchies-react/.mocharc.json, packages/hierarchies-react/package.json, packages/hierarchies/.mocharc.json, packages/hierarchies/package.json, packages/models-tree/package.json, packages/opentelemetry/package.json, packages/shared/.mocharc.json, packages/shared/package.json, packages/testing/package.json, packages/unified-selection/package.json, pnpm-lock.yaml
Looks like there is no need to use `source-map-support` with `mocha` since node v12.12.0. Updated scripts and debug config to use node's `--enable-source-maps` flag. https://mochajs.org/#-enable-source-maps
=> Remove source-map-support dependency

packages/hierarchies/src/hierarchies/HierarchyDefinition.ts, packages/hierarchies/src/hierarchies/HierarchyNode.ts, packages/hierarchies/src/hierarchies/HierarchyProvider.ts, packages/hierarchies/src/hierarchies/Logging.ts, packages/hierarchies/src/hierarchies/NodeSelectQueryFactory.ts
We're not publishing out docs to iTwin.js doc site, so it makes no sense to use double-brackets to reference APIs - use backticks instead.
=> hierarchies: Reference APIs using backticks rather than double-brackets

.changeset/smooth-fans-listen.md, packages/components/src/presentation-components/common/Utils.ts, packages/components/src/test/common/Utils.test.ts, packages/components/src/test/instance-filter-builder/PresentationInstanceFilter.test.ts
`PresentationInstanceFilter.toGenericInstanceFilter` was throwing error when condition contains numeric string `UniqueValue`. Fixed `deserializeUniqueValues` to correctly handle string values that are valid JSON but it not serialized `UniqueValue`s.
=> Fix `PresentationInstanceFilter.toGenericInstanceFilter` conversion with numeric string values

packages/hierarchies/api/presentation-hierarchies.api.md, packages/hierarchies/src/hierarchies/HierarchyProvider.ts, packages/hierarchies/src/test/HierarchyProvider.test.ts
Added support for `instanceFilter` and `hierarchyLevelSizeLimit` when loading node instance keys using `HierarchyProvider.getNodeInstanceKeys`
=> Add ability to load limited or filtered node instance keys

apps/test-app/frontend/src/components/tree-widget/stateless-v2/Tree.tsx, packages/hierarchies-react/api/presentation-hierarchies-react.api.md, packages/hierarchies-react/api/presentation-hierarchies-react.exports.csv, packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts, packages/hierarchies-react/src/test/UseTree.test.tsx
Hierarchy level size limit might be overridden for specific hierarchy level. This might be necessary information when building instance filter and checking if filter reduces instance count to set limit.
=> Expose hierarchy level size limit

.changeset/gorgeous-crabs-rhyme.md, packages/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.tsx, packages/components/src/test/tree/controlled/PresentationTreeRenderer.test.tsx
Disabled `onMouseDown` propagation for hierarchy filter buttons as they were causing duplicate `use-{tree}` feature reports in `TreeWidget`.
=> Disable onMouseDown propagation for hierarchy filter buttons

.changeset/odd-plums-marry.md, packages/components/src/presentation-components/tree/ReportingTreeNodeLoader.ts, packages/components/src/test/tree/ReportingTreeNodeLoader.test.ts
Moved nodes load duration reporting into `next` callback to make sure it is reported immediately after nodes are loaded. Reporting from `complete` callback leaves open possibility to unsubscribe between `next` and `complete` without reporting duration.
=> Make sure nodes load duration is reported always

apps/performance-tests/package.json
Script was not supposed to be removed with [537](https://github.com/iTwin/presentation/issues/537).
=> Missing benchmark script

apps/performance-tests/.mocharc.json, apps/performance-tests/src/main.ts, apps/performance-tests/src/util/BlockHandler.ts, apps/performance-tests/src/util/Logging.ts, apps/performance-tests/src/util/StatelessHierarchyProvider.ts, packages/hierarchies/src/hierarchies/HierarchyProvider.ts, packages/hierarchies/src/hierarchies/internal/TreeNodesReader.ts, packages/hierarchies/src/test/HierarchyProvider.test.ts, packages/hierarchies/src/test/internal/TreeNodesReader.test.ts
- Performance tests adjustments:
- Extract tests' logger into a separate module so it can be used not only to pass to hierarchies package, but also by the tests themselves
- Change performance tests' `expand` parallelism from `100` to `1`. Having a 100 parallel node requests doesn't really simulate a real world users' scenario and just causes a lot of main thread blocking simply because other tasks always have to wait for 100 other tasks to complete. **The change substantially reduces overall time needed to create hierarchies**, but this is a tests' change and what we really care is the library performance.
- Change the performance tests to not use query cache. This makes debugging easier and our performance measure independent of consumers' configuration.
- The query reader change …
=> hierarchies: Performance tests adjustment

packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts, packages/hierarchies-react/src/test/UseTree.test.tsx
Ignore errors thrown while loading filtered paths and show whole hierarchy.
=> Ignore error while loading filtered paths

packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/LocalizationContext.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeRenderer.tsx, packages/hierarchies/src/hierarchies/HierarchyProvider.ts
Switched to `Partial<LocalizedStrings>` instead of just `LocalizedStrings`.
=> Partial hierarchies localization

packages/models-tree/src/models-tree/ModelsTreeDefinition.ts
Part of https://github.com/iTwin/presentation/issues/597.
Often, to determine whether a Subject node needs to be displayed or not, we have to run a bunch of queries to see if its branch contains at least one Model with elements. However, with https://github.com/iTwin/presentation/pull/598, we already have that information, so here we just make use of it.
There're still a few cases that need to be look at.
=> `models-tree`: Pre-determine subjects' children flag

.changeset/pink-moose-drop.md, apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts, packages/hierarchies-react/src/test/UseTree.test.tsx
Updated `reloadTree` options to allow to notify `HierarchyProvider` about data changes. This makes sure that `HierarchyProvider` has cleared caches and pulls new data when tree is reloading.
=> Hierarchies-react: Reload tree on data change

.changeset/rare-pugs-sniff.md, packages/components/src/presentation-components/tree/controlled/UseUnifiedSelection.ts, packages/components/src/test/tree/controlled/UseUnifiedSelection.test.ts
Closes https://github.com/iTwin/presentation/issues/608.
=> `components`: Fix non-loaded nodes not being shift selected

.azure-pipelines/generate-docs.yaml
After https://github.com/iTwin/presentation/pull/594 docs pipeline was failing on non pull request builds as it was trying to detect changes. Changed `Check_Changes` to only run on pull requests.
=> Fix docs pipeline failing on non pull request builds

.changeset/rare-hotels-bathe.md, .changeset/rare-pugs-sniff.md, .changeset/tough-peaches-remain.md, .vscode/settings.json, packages/components/api/presentation-components.api.md, packages/components/src/presentation-components/tree/controlled/UseUnifiedSelection.ts, packages/components/src/test/tree/controlled/UseUnifiedSelection.test.ts
Backports PR that fixes unified selection in Tree:
* #493 
* #519 
* #609
=> Components: Backport Tree unified selection fixes

.changeset/six-students-play.md, packages/hierarchies/src/hierarchies/HierarchyDefinition.ts, packages/hierarchies/src/hierarchies/HierarchyNode.ts, packages/hierarchies/src/hierarchies/HierarchyNodeKey.ts
Using a type guard to get `@internal` type from a `@public` one makes linter angry, e.g.:
```ts
const node: HierarchyNode = getNode();
if (HierarchyNode.isLabelGroupingNode(node)) {
console.log(node.key.label);
}
```
gives:
=> `hierarchies`: Remove `@internal` tags from public APIs that aren't exported through the barrel

.changeset/orange-clocks-sin.md, apps/test-app/frontend/package.json, apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx, apps/test-app/frontend/vite.config.mts, packages/hierarchies-react/api/presentation-hierarchies-react.api.md, packages/hierarchies-react/api/presentation-hierarchies-react.exports.csv, packages/hierarchies-react/package.json, packages/hierarchies-react/src/presentation-hierarchies-react/UseSelectionHandler.ts, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx, packages/hierarchies-react/src/test/UseSelectionHandler.test.tsx, packages/hierarchies-react/src/test/itwinui/Tree.test.tsx, pnpm-lock.yaml
Changes needed for https://github.com/iTwin/viewer-components-react/issues/867. Also memoized the `onNodeClick` and `onNodeKeyDown` as `TreeRenderer` contains a hook that depends on them.
=> Hierarchies-react: pass node to `onNodeClick` instead of node ID

.changeset/rude-boxes-argue.md, packages/hierarchies/src/hierarchies/HierarchyProvider.ts, packages/hierarchies/src/test/HierarchyProvider.test.ts
Fixed `preProcessNode` and `postProcessNode` not retaining `this` context.
=> Hierarchies: fix `preProcessNode` and `postProcessNode` losing `this` context

.changeset/lucky-radios-trade.md, packages/hierarchies-react/src/presentation-hierarchies-react/UseSelectionHandler.ts, packages/hierarchies-react/src/test/UseSelectionHandler.test.tsx
Changed `extended` selection mode to not deselect nodes when `ctrl` is not used.
=> Hierarchies-react: Disable node deselection with extended selection mode

.changeset/odd-tables-occur.md, packages/shared/src/shared/ecsql-snippets/ECSqlJoinSnippets.ts, packages/shared/src/test/ecsql-snippets/ECSqlJoinSnippets.test.ts
A fix required for https://github.com/iTwin/viewer-components-react/issues/915.
Added more test cases for the function and changed existing ones to use real situations from `BisCore` schema.
Below are the matrices of where the navigation property should be located:
When doing a forward join:
| nav prop / relationship | forward | backward |
| ----------------------- | ------- | -------- |
| forward                 | src     | src      |
| backward                | target  | target   |
When doing a reversed join:
| nav prop / relationship | forward | backward |
| ----------------------- | ------- | -------- |
| forward                 | target  | target   |
| backward                | src     | src      |
Clearly, relationship strength direction doesn't affect this - we should look only at …
=> `shared`: Fix `ECSql.createRelationshipPathJoinClause`

.changeset/wise-beds-confess.md, packages/hierarchies/src/hierarchies/NodeSelectQueryFactory.ts, packages/hierarchies/src/test/NodeSelectQueryFactory.test.ts
Fixes needed for https://github.com/iTwin/viewer-components-react/issues/903.
=> Hierarchies: Fix like operator not matching substrings

.changeset/little-grapes-check.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.css
Not sure whether I did not save / did not commit the latest changes with https://github.com/iTwin/presentation/pull/644.
=> Hierarchies-react: fix filtering buttons not showing on hover

.changeset/modern-bikes-trade.md, packages/hierarchies-react/src/presentation-hierarchies-react/internal/TreeLoader.ts
Cannot use `instanceof` to detect rows limit error in case `hierarchies-react` uses different version of `hierarchies` than consumer defining hierarchy definition.
=> Do not use instanceof to detect rows limit error

.changeset/modern-parents-visit.md, packages/unified-selection/src/test/EnableUnifiedSelectionSyncWithIModel.test.ts, packages/unified-selection/src/unified-selection/EnableUnifiedSelectionSyncWithIModel.ts
Changed `handleIModelSelectionChange` to update selection storage with all changes at once instead of one by one as this improves performance and prevents storage from being unnecessarily cleaned when the same element is selected.
=> Unified-selection: batch iModel selection changes

.github/workflows/changeset-release.yml
The `changeset-release` pipeline requires some additional permissions when using `secrets.GITHUB_TOKEN`.
=> Update pipeline permissions

.changeset/stale-horses-grin.md, apps/test-app/frontend/package.json, packages/hierarchies-react/package.json, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx, packages/hierarchies-react/src/test/index.ts, pnpm-lock.yaml
`TreeNode` now provides proper `onClick` and `onKeyDown` so wrapping the node is no longer necessary.
=> Hierarchies-react: use `TreeNode` `onClick` and `onKeyDown` callbacks

.changeset/chilly-eagles-know.md, .changeset/dirty-dogs-run.md, apps/full-stack-tests/src/hierarchies/HierarchyFiltering.test.ts, apps/full-stack-tests/src/hierarchies/Utils.ts, packages/hierarchies-react/api/presentation-hierarchies-react.api.md, packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts, packages/hierarchies-react/src/test/UseTree.test.tsx, packages/hierarchies/api/presentation-hierarchies.api.md, packages/hierarchies/src/hierarchies/HierarchyNode.ts, packages/hierarchies/src/hierarchies/HierarchyProvider.ts, packages/hierarchies/src/hierarchies/internal/FilteringHierarchyDefinition.ts, packages/hierarchies/src/test/HierarchyProvider.test.ts, packages/hierarchies/src/test/internal/FilteringHierarchyDefinition.test.ts
Closes https://github.com/iTwin/presentation/issues/673.
=> Hierarchies: Allow disabling expansion to filter targets

.changeset/giant-comics-jump.md, .changeset/plenty-days-hug.md, apps/full-stack-tests/src/hierarchies-react/learning-snipptets/ReadmeExample.test.tsx, apps/full-stack-tests/src/hierarchies/HierarchyFiltering.test.ts, apps/full-stack-tests/src/hierarchies/HierarchyValidation.ts, apps/full-stack-tests/src/hierarchies/learning-snippets/HierarchyFiltering.test.ts, packages/hierarchies-react/README.md, packages/hierarchies/learning/HierarchyFiltering.md, packages/hierarchies/src/hierarchies/internal/FilteringHierarchyDefinition.ts, packages/hierarchies/src/test/HierarchyProvider.test.ts, packages/hierarchies/src/test/internal/FilteringHierarchyDefinition.test.ts, packages/models-tree/src/models-tree/ModelsTreeDefinition.ts, packages/shared/README.md, packages/shared/api/presentation-shared.api.md, packages/shared/src/shared/ecsql-snippets/ECSqlValueSelectorSnippets.ts, packages/shared/src/shared/ecsql-snippets/index.ts, packages/shared/src/test/ecsql-snippets/ECSqlValueSelectorSnippets.test.ts, packages/test-utilities/src/test-utilities/IModelUtils.ts
=> Hierarchies: Add a learning page for hierarchy filtering

apps/full-stack-tests/src/hierarchies/learning-snippets/Logging.test.ts, apps/performance-tests/package.json, apps/performance-tests/src/util/Logging.ts, packages/hierarchies/learning/Logging.md, packages/hierarchies/src/hierarchies/HierarchyProvider.ts, packages/hierarchies/src/hierarchies/LimitingECSqlQueryExecutor.ts, packages/hierarchies/src/hierarchies/internal/Common.ts, packages/hierarchies/src/hierarchies/internal/LoggingUtils.ts, packages/hierarchies/src/hierarchies/internal/operators/DetermineChildren.ts, packages/hierarchies/src/hierarchies/internal/operators/Grouping.ts, packages/hierarchies/src/hierarchies/internal/operators/HideIfNoChildren.ts, packages/hierarchies/src/hierarchies/internal/operators/HideNodesInHierarchy.ts, packages/hierarchies/src/test/HierarchyProvider.test.ts, pnpm-lock.yaml
=> Hierarchies: Cleanup logging, add a learning page

.changeset/twelve-otters-design.md, packages/components/src/presentation-components/properties/editors/NumericPropertyEditor.tsx, packages/components/src/presentation-components/properties/inputs/NumericPropertyInput.tsx, packages/components/src/test/properties/inputs/NumericPropertyInput.test.tsx
Changes for https://github.com/iTwin/appui/issues/915.
=> Components: Use raw value instead of display value in `NumericPropertyEditor`

.changeset/afraid-rats-attack.md, .changeset/big-pots-burn.md, apps/full-stack-tests/package.json, apps/full-stack-tests/src/Utils.ts, apps/full-stack-tests/src/components/tree/HierarchyLevelFiltering.test.tsx, apps/full-stack-tests/src/hierarchies-react/learning-snipptets/Localization.test.tsx, apps/full-stack-tests/src/hierarchies-react/learning-snipptets/ReadmeExample.test.tsx, apps/test-app/frontend/package.json, packages/components/.mocharc.json, packages/components/package.json, packages/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.tsx, packages/components/src/test/_helpers/Common.ts, packages/components/src/test/instance-filter-builder/IntanceFilterBuilder.test.tsx, packages/components/src/test/instance-filter-builder/PresentationFilterBuilder.test.tsx, packages/components/src/test/instance-filter-builder/PresentationInstanceFilterDialog.test.tsx, packages/components/src/test/tree/controlled/PresentationTreeRenderer.test.tsx, packages/hierarchies-react/api/presentation-hierarchies-react.api.md, packages/hierarchies-react/api/presentation-hierarchies-react.exports.csv, packages/hierarchies-react/package.json, packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx, packages/hierarchies-react/src/test/TestUtils.ts, packages/hierarchies-react/src/test/itwinui/Tree.test.tsx, pnpm-lock.yaml
Bumped iTwinUI version.
Fixed warnings about passing ref to the component that does not use `forwardRef`
Updated `IconButton` usage to use `label` instead of `title`.
Updated tests to work with latest iTwinUI changes.
=> Bump ITwinUI

.changeset/shiny-humans-hug.md, .changeset/short-jars-sing.md, apps/full-stack-tests/src/hierarchies-react/learning-snipptets/Localization.test.tsx, apps/full-stack-tests/src/hierarchies/Formatting.test.ts, apps/full-stack-tests/src/hierarchies/Update.test.ts, apps/full-stack-tests/src/hierarchies/learning-snippets/Formatting.test.ts, packages/hierarchies-react/README.md, packages/hierarchies/learning/Formatting.md, packages/hierarchies/src/hierarchies/HierarchyProvider.ts, packages/hierarchies/src/test/internal/TreeNodesReader.test.ts, packages/shared/README.md, packages/shared/api/presentation-shared.api.md, packages/shared/src/shared/ConcatenatedValue.ts, packages/shared/src/shared/Formatting.ts, packages/shared/src/shared/Values.ts, packages/shared/src/shared/ecsql-snippets/ECSqlValueSelectorSnippets.ts, packages/shared/src/shared/ecsql-snippets/index.ts, packages/shared/src/test/ConcatenatedValue.test.ts, packages/shared/src/test/Formatting.test.ts, packages/shared/src/test/InstanceLabelSelectClauseFactory.test.ts, packages/shared/src/test/ecsql-snippets/ECSqlValueSelectorSnippets.test.ts
Part of https://github.com/iTwin/presentation/issues/702.
With upcoming changes to support nodes being loaded from different imodels or even other sources, we want to avoid having dependency on an iModel (or its schema provider) after loading the nodes. This PR moves property metadata extraction from when we process the nodes to when we create a query.
=> Shared: Don't require schema provider when formatting `ConcatenatedValue`

.changeset/gorgeous-dingos-clap.md, packages/hierarchies/src/hierarchies/imodel/IModelHierarchyProvider.ts, packages/hierarchies/src/hierarchies/imodel/operators/Grouping.ts, packages/hierarchies/src/hierarchies/internal/Common.ts, packages/hierarchies/src/test/imodel/IModelHierarchyProvider.test.ts
Fixed iModel hierarchy provider returning unfiltered nodes after setting the hierarchy filter in certain scenarios.
The situation could happen when a new hierarchy filter is set during an ongoing nodes request. Then, requesting nodes immediately after setting the filter could return nodes from the previous request.
The change also slightly changes what happens with ongoing requests when hierarchy provider's internal state is reset: provider is disposed, the `imodelChanged` event is raised or hierarchy filter is set. Previously, it would continue handling all ongoing requests and return a valid result. Now, it will stop ASAP and return an empty list.
=> Hierarchies: Fix hierarchy filtering

.changeset/funny-candles-double.md, packages/unified-selection/src/test/HiliteSetProvider.test.ts, packages/unified-selection/src/test/Selectable.test.ts, packages/unified-selection/src/test/SelectionStorage.test.ts, packages/unified-selection/src/test/_helpers/SelectablesCreator.ts, packages/unified-selection/src/unified-selection/HiliteSetProvider.ts, packages/unified-selection/src/unified-selection/Selectable.ts
The provider wouldn't properly cache class check result for a selectable instance key if its class name was specified in the `Schema.Class` format rather than `Schema:Class`.
=> Unified selection: Fix hilite set provider class check caching

.changeset/config.json
=> `changesets` should ignore app and test packages

packages/components/package.json
Looks like in `presentation-components` package the coverage numbers are flaky due to the tests being run in parallel. Changing them to run sequentially until I find the culprit.
=> `components`: Run tests sequentially to avoid coverage flakiness

.changeset/lazy-buttons-grab.md, packages/core-interop/.npmignore, packages/hierarchies/.npmignore, packages/opentelemetry/.npmignore, packages/testing/.npmignore
Updated npmignore to include dummy package.json that is needed for package to work as commonjs module.
=> Deliver cjs package.json

apps/full-stack-tests/src/setup.ts, packages/components/package.json, packages/components/src/test/setup.ts, packages/hierarchies-react/src/test/setup.ts
Closes https://github.com/iTwin/presentation/issues/762.
I did not get to the bottom of this... What I determined is that `c8` has nothing to do with this. Running `mocha` tests in parallel mode with `NODE_V8_COVERAGE` set to some directory randomly skips some APIs from coverage results. The higher the parallelism - the higher the miss chance. This must be related to when `v8` takes coverage and how `mocha` terminates the worker processes - probably the process gets terminated before `v8` finishes taking coverage results for that process. Adding a `v8.takeCoverage()` call after a test suite run seems to take care of that. Added it to all packages that run tests in parallel. Calling the function seems to have no effect if `NODE_V8_COVERAGE` is not set.
=> Run tests for coverage in parallel mode

.changeset/poor-badgers-sparkle.md, packages/unified-selection/api/unified-selection.api.md, packages/unified-selection/api/unified-selection.exports.csv, packages/unified-selection/src/test/Selectable.test.ts, packages/unified-selection/src/unified-selection.ts, packages/unified-selection/src/unified-selection/Selectable.ts
Class name used in transient element instance key does not follow ECSchema class name formats: Schema:Class or Schema.Class.
Added exception for transient element instance key when normalizing class names.
=> Unified selection: fix transient elements support

.changeset/odd-steaks-occur.md, packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts, packages/hierarchies-react/src/test/UseTree.test.tsx
Fixed double tree load happening if `getFilteredPaths` are provided during first render. One load is started when hierarchies provider is created and second is started after filtered paths are loaded.
After this change tree load will start only after filtered paths are loaded to avoid unnecessary loading unfiltered tree that will be immediately discarded.
=> [hierarchies-react]: Avoid double tree load

.changeset/rude-ligers-vanish.md, .changeset/strong-cherries-sort.md, apps/full-stack-tests/src/hierarchies/HierarchyFiltering.test.ts, apps/full-stack-tests/src/hierarchies/learning-snippets/CustomHierarchyProvider.test.ts, apps/performance-tests/src/hierarchies/Filtering.test.ts, apps/test-app/backend/src/SampleRpcImpl.ts, apps/test-app/common/src/SampleRpcInterface.ts, apps/test-app/frontend/package.json, apps/test-app/frontend/src/components/app/App.tsx, apps/test-app/frontend/src/components/tree-widget/MultiDataSourceTree.tsx, apps/test-app/frontend/vite.config.mts, packages/hierarchies/README.md, packages/hierarchies/api/presentation-hierarchies.api.md, packages/hierarchies/api/presentation-hierarchies.exports.csv, packages/hierarchies/learning/CustomHierarchyProviders.md, packages/hierarchies/src/hierarchies/HierarchyFiltering.ts, packages/hierarchies/src/hierarchies/HierarchyNode.ts, packages/hierarchies/src/hierarchies/HierarchyProvider.ts, packages/hierarchies/src/hierarchies/imodel/FilteringHierarchyDefinition.ts, packages/hierarchies/src/hierarchies/imodel/PredicateBasedHierarchyDefinition.ts, packages/hierarchies/src/presentation-hierarchies.ts, packages/hierarchies/src/test/imodel/FilteringHierarchyDefinition.test.ts, packages/hierarchies/src/test/imodel/IModelHierarchyProvider.test.ts, packages/hierarchies/src/test/imodel/PredicateBasedHierarchyDefinition.test.ts, pnpm-lock.yaml
Closes https://github.com/iTwin/presentation/issues/749
Additionally, added an API that helps with hierarchy filtering implementation. Refactored imodel hierarchy provider to use that API and filtering performance improved by ~25%:
| Benchmark suite | Current: 4f50cafc12c043cafa467d7341640cfff8a9eb2d | Previous: 9374049632acf91de7018d02b49660b11e53caa6 | Deviation | Status |
|-|-|-|-|-|
| `filtering filters with 50000 paths` | `9974.49` ms | `13770.6` ms | `-27.5668%` | ✅ |
=> Hierarchies: Custom hierarchy providers learning

.vscode/launch.json, apps/full-stack-tests/scripts/setup-tests.cjs, apps/full-stack-tests/src/IntegrationTests.ts
Full stack tests run in parallel, and the ones that use `IModelHost` pass it the `.cache` directory for various caches. The host attempts to create one if it doesn't exist. However, when multiple processes attempt to do that at the same time, we sometimes get an error like this:
```
EEXIST: file already exists, mkdir '{repo-root}\apps\full-stack-tests\lib\.cache'
```
Now we create it up front, when building the tests and setting them up.
=> Fix full stack tests flakiness

.changeset/neat-carpets-melt.md, .changeset/thick-books-itch.md, apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx, packages/components/src/presentation-components/properties/inputs/UniquePropertyValuesSelector.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx, pnpm-lock.yaml, pnpm-workspace.yaml
Upgraded itwinui-react to the latest version.
Added missing `ref` props to placeholder and error nodes renderer in `TreeNodeRenderer` from `hierarchies-react`
Updated `UniqueValuesSelector` to not clear filter when value is selected. Added filter cleanup on dropdown menu close to make it consistent with default behavior.
=> Itiwnui-react upgrade

.changeset/afraid-ducks-listen.md, .changeset/seven-turtles-train.md, packages/hierarchies-react/api/presentation-hierarchies-react.api.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.css, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeRenderer.tsx, packages/models-tree/tsconfig.json
Adjusted size of tree node loading indicator in small tree to match other icons.
Before:
After:
=> `hierarchies-react`: adjust tree node loading indicator in small tree

.changeset/selfish-toes-promise.md, packages/hierarchies-react/README.md, packages/hierarchies-react/api/presentation-hierarchies-react.api.md, packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts, packages/hierarchies-react/src/presentation-hierarchies-react/internal/UseUnifiedSelection.ts, packages/hierarchies-react/src/test/UseTree.test.tsx, packages/hierarchies-react/src/test/internal/UseUnifiedSelection.test.tsx
Prerequisite for adding a selection predicate (https://github.com/iTwin/viewer-components-react/issues/1099)
=> `hierarchies-react`: Add `getNode` function to tree state hooks

.changeset/fresh-dryers-return.md, apps/full-stack-tests/src/hierarchies-react/learning-snipptets/Localization.test.tsx, apps/full-stack-tests/src/hierarchies-react/learning-snipptets/ReadmeExample.test.tsx, apps/full-stack-tests/src/hierarchies/Utils.ts, apps/full-stack-tests/src/hierarchies/learning-snippets/HierarchyFiltering.test.ts, apps/full-stack-tests/src/hierarchies/learning-snippets/ReadmeExample.test.ts, packages/core-interop/README.md, packages/core-interop/api/presentation-core-interop.api.md, packages/core-interop/api/presentation-core-interop.exports.csv, packages/core-interop/src/core-interop/IModelKey.ts, packages/core-interop/src/presentation-core-interop.ts, packages/core-interop/src/test/IModelKey.test.ts, packages/hierarchies-react/README.md, packages/hierarchies/README.md, packages/hierarchies/learning/imodel/HierarchyFiltering.md, packages/hierarchies/learning/imodel/HierarchyProvider.md, packages/unified-selection/README.md, packages/unified-selection/src/unified-selection/EnableUnifiedSelectionSyncWithIModel.ts, packages/unified-selection/src/unified-selection/SelectionStorage.ts
Turns out `BlankConnection` always has an empty `key`, so we should fall back to `name`. Provide an utility for that to ensure consistent imodel identifiers.
=> `core-interop`: Add a `createIModelKey` function to safely create an identifier for an `IModel` in different situations

packages/hierarchies/learning/CustomHierarchyProviders.md
Turns out our "Validate docs" pipeline wasn't required, so https://github.com/iTwin/presentation/pull/816 merged with failing docs validation.
=> `hierarchies`: Update extractions

.changeset/pink-paws-refuse.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.css, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/1117
https://github.com/user-attachments/assets/528a1ee2-c5a7-42ee-b322-c2af697bd456
Still need to check if visibility button also causes the same bug.
=> [Tree Node Renderer]: Filter button visibility fix

apps/full-stack-tests/src/IModelUtils.ts, apps/load-tests/backend/src/main.ts
nativeDb was removed in itwinjs core v5.
This is needed for https://github.com/iTwin/presentation/pull/834
=> Remove nativeDb usage

.github/workflows/extract-api.yaml
There was a problem with extract-api pipeline: if changes were made only in `/apps` folder, the extract-api job wouldn't run. Because of this, PRs couldnt be completed.
=> Update extract-api yml file

pnpm-lock.yaml
Closes https://github.com/iTwin/presentation/security/dependabot/41
=> Bump `undici` dependency

.pnpmfile.cjs, apps/test-app/frontend/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Updated appui dependencies to v5.1, this allows us to remove core-telemetry package since it is no longer a peer dependency.
=> Remove core-telemetry package from test-app

.changeset/clever-boats-knock.md, .changeset/famous-bags-pull.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeActionButtons.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
Filter icon style fix
Removed filter reset button.
=> `hierarchies-react`: Cleanup filtering action buttons

.changeset/stupid-mugs-dress.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
Fixes https://github.com/iTwin/viewer-components-react/issues/1158
| Before | After |
|-|-|
| ![image](https://github.com/user-attachments/assets/a41a116b-9d19-49b2-8dfc-9189273a6970) | ![image](https://github.com/user-attachments/assets/20e52964-ab2a-4de4-80f6-5d950d536b7e) |
=> [hierarchies-react]: Fix hierarchy level size limit message in narrow tree

.changeset/swift-hats-fail.md, packages/components/src/presentation-components/common/Utils.ts, packages/components/src/presentation-components/propertygrid/UseUnifiedSelection.tsx, packages/components/src/presentation-components/viewport/ViewportSelectionHandler.ts, packages/components/src/test/propertygrid/UseUnifiedSelection.test.tsx
Some resource used from `itwinjs-core` do not have `Symbol.dispose` in 4.x versions. Need to make sure that we check if resource supports the new `Symbol.dispose` for disposal to work properly.
=> [components]: Properly dispose resources

.changeset/real-pets-cover.md, apps/test-app/frontend/src/components/tree-widget/StatelessTree.tsx, packages/hierarchies-react/api/presentation-hierarchies-react.api.md, packages/hierarchies-react/api/presentation-hierarchies-react.exports.csv, packages/hierarchies-react/src/presentation-hierarchies-react.ts, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeActionButton.css, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeActionButton.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeActionButtons.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeRenderer.tsx
When multiple actions are provided:
When one action is provided:
When no actions are provided:
Keeping icon button position in the same place when other icon buttons are not displayed:
When dropdown actions exist but none are visible for a node.
=> [Hierarchies-react]: add dropdown button actions

.changeset/long-news-push.md, .changeset/selfish-chefs-raise.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.css, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
This PR includes couple fixes for Tree component on touch devices:
- Fixed tree node requiring two click to expand on touch devices when node has filtering buttons. https://github.com/iTwin/viewer-components-react/issues/1156
- Fixed hierarchy level size exceeded message not being wrapped on Safari. Previous example didn't work on all browsers https://github.com/iTwin/presentation/pull/866
=> [hierarchies-react]: Fixes for Tree component on touch devices

.changeset/plenty-boats-judge.md, apps/test-app/frontend/package.json, packages/hierarchies-react/package.json, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeErrorRenderer.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx, pnpm-lock.yaml
Updated itwinUI to alpha.8, this makes `variant` a required prop for text, which we use in node errors.
Sub label visuals:
Error nodes are still broken, but chose a variant that would not brake it further (with text size). This should be fixed when we get tree error items.
=> [Hierarchy-react]: kiwi tree sub label

.changeset/hungry-berries-sort.md, packages/unified-selection/api/unified-selection.api.md, packages/unified-selection/api/unified-selection.exports.csv, packages/unified-selection/learning/MigrationGuide.md, packages/unified-selection/src/unified-selection.ts, packages/unified-selection/src/unified-selection/EnableUnifiedSelectionSyncWithIModel.ts, packages/unified-selection/src/unified-selection/SelectionScope.ts
Closes https://github.com/iTwin/presentation/issues/900.
The guide is based on this PR in `viewer` repo: https://github.com/iTwin/viewer/pull/346.
=> Unified selection: Add a "Selection scopes" section to migration guide

.changeset/four-shoes-repeat.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeRenderer.tsx
Fixed tree nodes overlapping if nodes with and without sublabel are rendered alongside.
=> [hierarchies-react]: Fix nodes overlapping

.changeset/brown-areas-serve.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx, packages/hierarchies-react/src/test/itwinui/Tree.test.tsx
Part of https://github.com/iTwin/viewer-components-react/issues/1239
Update message rendered when hierarchy level size limit is exceeded to take into account if that level is filterable.
=> [hierarchies-react]: Do not suggest filtering if hierarchy level does not supports it.

.changeset/young-forks-punch.md, packages/hierarchies-react/api/presentation-hierarchies-react.api.md, packages/hierarchies-react/src/presentation-hierarchies-react.ts
`@itwin/presentation-hierarchies` is a direct dependency for `presentation-hierarchies-react`, so there's no way to set a logger to the underlying `presentation-hierarchies` for `presentation-hierarchies-react` consumers without it re-exporting those functions.
=> Re-export get/set logger functions from `presentation-hierarchies`

apps/full-stack-tests/src/IModelUtils.ts, apps/full-stack-tests/src/IntegrationTests.ts, apps/full-stack-tests/src/components/tree/TreeDataProvider.test.ts, apps/full-stack-tests/src/hierarchies/Formatting.test.ts, packages/components/src/presentation-components/tree/Utils.ts, packages/components/src/test/common/Utils.test.ts, packages/core-interop/src/core-interop/Formatting.ts, packages/core-interop/src/core-interop/MetadataInternal.ts, packages/core-interop/src/test/Formatting.test.ts, packages/core-interop/src/test/Metadata.test.ts, packages/test-utilities/src/test-utilities/IModelUtils.ts, packages/testing/src/presentation-testing/Helpers.ts, pnpm-lock.yaml, pnpm-workspace.yaml, scripts/regression/core-4.10.7.patch, scripts/regression/core-4.4.0.patch
- Use latest `5.0-rc` as dev dependencies
- Use latest `4.11.1` as direct dependencies
- Make sure we stay compatible with `4.x` as well as `5.0`
=> Bump `itwinjs-core` dependencies

.changeset/thirty-ends-sit.md, packages/hierarchies-react/src/presentation-hierarchies-react/stratakit/TreeRenderer.tsx
Some of our component props were passed down to `PlaceholderNode` component that resulted in console errors.
=> [hierarchies-react]: Avoid leaking props

apps/full-stack-tests/src/Utils.ts, apps/full-stack-tests/src/components/properties/PresentationFilterBuilderValueRenderer.test.tsx, apps/full-stack-tests/src/components/tree/HierarchyLevelFiltering.test.tsx, apps/full-stack-tests/src/hierarchies-react/learning-snipptets/Localization.test.tsx, apps/full-stack-tests/src/hierarchies-react/learning-snipptets/ReadmeExample.test.tsx, apps/full-stack-tests/src/unified-selection-react/learning-snippets/ReadmeExample.test.tsx, apps/full-stack-tests/src/unified-selection/learning-snippets/ReadmeExample.test.tsx, packages/components/src/test/_helpers/Common.ts, packages/components/src/test/instance-filter-builder/IntanceFilterBuilder.test.tsx, packages/components/src/test/instance-filter-builder/PresentationFilterBuilder.test.tsx, packages/components/src/test/instance-filter-builder/PresentationInstanceFilterDialog.test.tsx, packages/components/src/test/properties/editors/NavigationPropertyEditor.test.tsx, packages/components/src/test/properties/inputs/NavigationPropertyTargetSelector.test.tsx, packages/components/src/test/properties/inputs/UniquePropertyValuesSelector.test.tsx, packages/components/src/test/tree/controlled/PresentationTreeRenderer.test.tsx, packages/hierarchies-react/src/test/TestUtils.ts, packages/hierarchies-react/src/test/itwinui/Tree.test.tsx, pnpm-lock.yaml, pnpm-workspace.yaml
Updated mocks to make sure that unit tests with virtualized components works with the newer `@tanstack/virtual` versions.
=> Make sure unit tests with virtualized components works

.changeset/fluffy-oranges-raise.md, packages/hierarchies-react/api/presentation-hierarchies-react.api.md, packages/hierarchies-react/api/presentation-hierarchies-react.exports.csv, packages/hierarchies-react/src/presentation-hierarchies-react.ts, packages/hierarchies-react/src/presentation-hierarchies-react/UseSelectionHandler.ts, packages/hierarchies-react/src/presentation-hierarchies-react/stratakit/RootErrorRenderer.tsx
In some cases, consumers might want to have some of the required props for `StrataKitTreeRenderer` defined in the same component where `StrataKitTreeRenderer` is returned. With the current implementation that would require some kind of work around to get the ` TreeRendererProps`. This is the case because Pick<ReturnType<useTree>, "TreeRendererProps"> will not return the `TreeRendererProps` as it not always exists. To avoid confusion and to make the consumption easier exposing `TreeRendererProps` would be benefitial.
```ts
function Tree (props: propsType) {
const useTree = useTree({...props})
...
if (useTree.rootErrorRenderer !== undefined) {
return <StrataKitRootErrorRenderer {...useTree.rootErrorRenderer} />
} 
return <MyTreeRenderer treeRendererProps={useTree.treeRendererProps} /> 
} …
```
=> [Hierarchy-react]: expose `TreeRendererProps`

.changeset/brown-peaches-smash.md, .npmrc, apps/test-app/frontend/src/components/tree-widget/TreeRendererWithFilterAction.tsx, packages/hierarchies-react/api/presentation-hierarchies-react.api.md, packages/hierarchies-react/api/presentation-hierarchies-react.exports.csv, packages/hierarchies-react/src/presentation-hierarchies-react.ts, packages/hierarchies-react/src/presentation-hierarchies-react/stratakit/LocalizationContext.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/stratakit/RenameAction.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/stratakit/TreeNodeRenderer.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/stratakit/TreeRenderer.tsx
Added ability to edit node labels. 
Added `Rename` action that initiates label editing.
=> [hierarchies-react]: Add ability to edit node labels

.changeset/honest-rooms-strive.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.css
Fixes https://github.com/iTwin/viewer-components-react/issues/1323
=> [hierarchies-react]: Do not show focus outline on mobile devices

.changeset/proud-jeans-bow.md, packages/hierarchies-react/src/presentation-hierarchies-react/UseTree.ts, packages/hierarchies-react/src/test/UseTree.test.tsx
We can determine if skeleton tree should be loaded if `treeRendererProps?.rootNodes === undefined` or `isReloading === true` (https://github.com/iTwin/contextual-tree-control-react/blob/b080b65804ca66cb18c197c200749c1171e93557/packages/resources-browser-react/src/resources-browser-react/components/ResourcesBrowserTree.tsx#L46). 
There is a problem when using filtering - tree flickers. Right now `isReloading` is set to true only while filtering paths are being retrieved and set.  Before [this](https://github.com/iTwin/presentation/pull/961/files?diff=split&w=0#diff-0f1fbbfa5df647ea9653681a8e33c21da1ede66f6df3c570bf1a65f09aad4aff:~:text=isReloading%3A%20isFiltering%2C) we had additional condition that checked if root nodes were loading. This condition helped with flickering problem, adding …
=> Adjust how `isReloading` is determined

.github/workflows/regression.yml
Added additional job to regression pipeline that checks if current PR title starts with `Release packages`. It title matches condition regression workflow is skipped. This should disable regression workflow running on release PRs that is failing because local package versions are already bumped and pnpm fails to resolve dependencies.
Closes https://github.com/iTwin/presentation/issues/984
=> Do not run regression workflow on release PRs

.changeset/shiny-years-draw.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx, packages/hierarchies-react/src/test/itwinui/Tree.test.tsx
Closes https://github.com/iTwin/presentation/issues/999
Tree widget e2e tests revealed that `Apply filter` button is not focused after hierarchy filter is applied. Added code to make sure that button is focused when hierarchy level is filtered.
=> [hierarchies-react] Focus apply filter button

.changeset/bright-poets-hug.md, apps/full-stack-tests/src/hierarchies/learning-snippets/HierarchyFiltering.test.ts, packages/hierarchies/api/presentation-hierarchies.api.md, packages/hierarchies/api/presentation-hierarchies.exports.csv, packages/hierarchies/learning/HierarchyFiltering.md, packages/hierarchies/src/hierarchies/HierarchyFiltering.ts, packages/hierarchies/src/hierarchies/imodel/FilteringHierarchyDefinition.ts, packages/hierarchies/src/test/HierarchyFiltering.test.ts, packages/hierarchies/src/test/imodel/FilteringHierarchyDefinition.test.ts
With `HierarchyFilteringPathOptions.autoExpand` set to `{ depth: number }` some nodes were not getting autoExpand propery set to `true`. 
If each node in hierarchy would be grouped and we had these filtered paths:
```ts
const filterPaths: HierarchyFilteringPath[] = [
{ path: [element, element2, element3], options: { autoExpand: { depth: 2 } } }
]
```
We would expect `element2` to have `autoExpand` set to `true`. But it didn't.
Added `includeGroupingNodes` to `FilteringPathAutoExpandOption` which allows expanding only desired grouping nodes.
=> Fix autoExpand depth not working correctly with grouping nodes

packages/unified-selection/learning/MigrationGuide.md
Closes https://github.com/iTwin/presentation/issues/1008
=> Unified selection: Highlight incompatibility of `enableUnifiedSelectionSyncWithIModel` and `viewWithUnifiedSelection`

.changeset/eager-needles-shave.md, packages/hierarchies-react/api/presentation-hierarchies-react.api.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/LocalizationContext.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeRenderer.tsx, packages/hierarchies-react/src/test/itwinui/Tree.test.tsx
Prerequisite for https://github.com/iTwin/viewer-components-react/issues/1367
Added support for custom tree node actions. To keep implementation simple and avoid complications of overflow all additional actions are rendered inside a dropdown menu under `More` button. Only filtering buttons are rendered on node directly.
=> [hierarchies-react]: Support custom tree node actions

.changeset/clean-steaks-matter.md, packages/components/api/presentation-components.api.md, packages/components/src/presentation-components/common/ContentDataProvider.ts, packages/components/src/test/common/ContentDataProvider.test.ts, packages/components/src/test/propertygrid/DataProvider.test.ts
https://github.com/iTwin/viewer-components-react/pull/1404 revealed that property widget doesn't automatically update with new format settings when they change in the formats provider.
=> Components: Fix content data providers not reacting to formats' changes

.changeset/tired-words-stop.md, packages/components/src/presentation-components/properties/inputs/UseQuantityValueInput.tsx, packages/components/src/test/properties/inputs/UseQuantityValueInput.test.tsx
Updated quantity properties editor to react and rerender value when format settings changes. Tested with https://github.com/iTwin/viewer-components-react/pull/1404
=> [components]: Quantity editor should react to format settings change

.changeset/public-flies-show.md, packages/hierarchies-react/src/presentation-hierarchies-react/itwinui/TreeNodeRenderer.tsx
Added tooltip for tree nodes. Used native browser tooltips through `title` prop so it should not block interactions with other nodes. Fixes https://github.com/iTwin/viewer-components-react/issues/1422
=> [hierarchies-react] Add tree node tooltip

.changeset/lucky-mirrors-allow.md, packages/hierarchies-react/src/presentation-hierarchies-react/UseNodeHighlighting.tsx, packages/hierarchies-react/src/test/UseNodeHighlighting.test.tsx
Change is based on https://github.com/iTwin/viewer-components-react/pull/1417
=> [Hierarchies react]: Change `useNodeHighlighting` hook to only highlight nodes that are filter targets

.changeset/young-pens-tease.md, apps/full-stack-tests/src/IntegrationTests.ts, apps/full-stack-tests/src/Utils.ts, apps/full-stack-tests/src/components/tree/Update.test.tsx, apps/load-tests/backend/src/main.ts, apps/load-tests/tests/src/processors/models-tree.ts, packages/components/src/presentation-components/common/StyleHelper.ts, packages/components/src/presentation-components/properties/inputs/UseQuantityValueInput.tsx, packages/components/src/presentation-components/table/UsePresentationTable.ts, packages/components/src/test/_helpers/Hierarchy.ts, packages/components/src/test/common/StyleHelper.test.ts, packages/components/src/test/properties/inputs/UniquePropertyValuesSelector.test.tsx, packages/components/src/test/tree/Utils.test.ts, packages/testing/src/presentation-testing/Helpers.ts, packages/testing/src/test/Helpers.test.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Fixes: https://github.com/iTwin/presentation/issues/1056
Requires: https://github.com/iTwin/itwinjs-core/pull/8502
Before:
After:
=> [components]: Use higher precision for KOQ values editing
